# Generated by Django 3.1.2 on 2020-10-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=15)),
                ('bed', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('street', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('zip_code', models.CharField(max_length=15)),
                ('lat_long', models.JSONField(default=[])),
            ],
        ),
    ]
