# Generated by Django 3.1.2 on 2020-10-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20201028_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_level',
            field=models.CharField(max_length=100),
        ),
    ]
